language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t api-feed ./udagram-api-feed/
  - docker build -t api-user ./udagram-api-user/
  - docker build -t frontend ./udagram-frontend/
  - docker build -t revproxy ./udagram-revproxy/
  - docker tag api-feed nirmalnr/api-feed:latest
  - docker tag api-user nirmalnr/api-user:latest
  - docker tag frontend nirmalnr/frontend:latest
  - docker tag revproxy nirmalnr/revproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push nirmalnr/api-feed
  - docker push nirmalnr/api-user
  - docker push nirmalnr/frontend
  - docker push nirmalnr/revproxy
